# This exists as our open data pipeline.
# It runs the opendata-pipeline CLI app with some enhancements for CI/CD.

name: OpenData Pipeline

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 5 * * 1"

  # can do manually
  workflow_dispatch:

# making executive decision to setup the project in multiple jobs so that we can run in parallel
# as opposed to one `poetry install --only main` but sequential running

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # fetch the data
  fetch-data:
    name: Fetch Data

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # checkout
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Poetry
        run: pipx install poetry

      # setup python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "poetry"

      # install latest version of CLI
      - name: Install Dependencies
        run: poetry install --only main

      # initialize data dir
      - name: Initialize App
        run: poetry run opendata-pipeline init

      # fetch records
      - name: Run fetching
        # here we can read local (which is latest remote)
        # BUT we still need to update the remote
        run: poetry run opendata-pipeline fetch --update-remote
        # removed `--update-remote` flag while testing
        # run: poetry run opendata-pipeline fetch
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Drug Prep Artifact
        uses: actions/upload-artifact@v3
        with:
          name: drug-files
          path: data/*_drug_prep.csv

      - name: Upload Records Artifact
        uses: actions/upload-artifact@v3
        with:
          name: records-files
          path: data/*_records.jsonl

  # extract drugs from the data
  extract-drugs:
    name: Extract Drugs

    # requires data to be fetched
    needs: fetch-data

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # checkout
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Poetry
        run: pipx install poetry

      # setup python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "poetry"

      # install latest version of CLI
      - name: Install Dependencies
        run: poetry install --only main

      # download drug_prep records (should be in data folder)
      - name: Download Drug Prep Artifact
        uses: actions/download-artifact@v3
        with:
          name: drug-files
          path: data
      # install rust CLI program
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Setup cache
        id: cache-cargo
        uses: actions/cache@v3
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-cargobin

      - name: Install Drug Extraction Toolbox
        # use || true if already installed (in cache)
        run: cargo install drug-extraction-cli || true

      - name: Run drug extraction
        # again we don't need to `--use-remote` because we checked it out
        run: poetry run opendata-pipeline extract-drugs

      # Upload drug data file artifact
      - uses: actions/upload-artifact@v3
        with:
          name: drug-output
          path: data/drug_*

  # geocode the data
  geocode:
    name: Geocode

    # requires data to be fetched
    needs: fetch-data

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # checkout
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Poetry
        run: pipx install poetry

      # setup python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "poetry"

      # install latest version of CLI
      - name: Install Dependencies
        run: poetry install --only main

      # download records (should be in data folder)
      - name: Download Records Artifact
        uses: actions/download-artifact@v3
        with:
          name: records-files
          path: data

      - name: Run geocoding
        # again we don't need to `--use-remote` because we checked it out
        run: poetry run opendata-pipeline geocode
        # use env here to scope to this command
        env:
          # get from github secrets
          ARCGIS_API_KEY: ${{ secrets.ARCGIS_TOKEN }}

      # Upload geocoding file artifact
      - uses: actions/upload-artifact@v3
        with:
          name: geocoding-output
          path: data/geocoded_data.jsonl

  # analyze/combine the data
  join:
    name: Join Files

    # requires data to be fetched
    needs: [extract-drugs, geocode]

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # checkout
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Poetry
        run: pipx install poetry

      # setup python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
          cache: "poetry"

      # install latest version of CLI
      - name: Install Dependencies
        run: poetry install --only main

      # download records (should be in data folder)
      - name: Download Records Artifact
        uses: actions/download-artifact@v3
        with:
          name: records-files
          path: data

      # download records (should be in data folder)
      - name: Download Drug Artifact
        uses: actions/download-artifact@v3
        with:
          name: drug-output
          path: data

      # download records (should be in data folder)
      - name: Download Geocoding Artifact
        uses: actions/download-artifact@v3
        with:
          name: geocoding-output
          path: data

      - name: Run analyzer
        run: poetry run opendata-pipeline analyze

      - name: Run geospatial joining
        run: poetry run opendata-pipeline spatial-join

      - name: Upload Spatial Join Records
        uses: actions/upload-artifact@v3
        with:
          name: spatial-join-records
          path: data/*_wide_form.csv

  profile:
    name: Profile

    # requires data to be joined
    needs: [join]

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # checkout
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Poetry
        run: pipx install poetry

      # setup python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          # TODO: have to use 3.10 until pandas-profiling supports 3.11
          python-version: "3.10"
          cache: "poetry"

      # download records (should be in data folder)
      - name: Download Records Artifact
        uses: actions/download-artifact@v3
        with:
          name: spatial-join-records
          path: data

      # download drug files (should be in data folder)
      - name: Download Records Artifact
        uses: actions/download-artifact@v3
        with:
          name: drug-output
          path: data
  
      - name: Install pandas-profiling
        # TODO: specify 3.10 until 3.11 supported
        run: pipx install --python python3.10 pandas-profiling

      - name: Run profiling
        run: ./scripts/profile.sh

      - name: Prepare Data for Release Assets
        run: ./scripts/prepare_data_release.sh

      - name: Upload assets artifact
        uses: actions/upload-artifact@v3
        with:
          name: release-assets
          path: assets

  release:
    name: Release Data

    needs: profile

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Download Records Artifact
        uses: actions/download-artifact@v3
        with:
          # should now be in assets folder
          name: release-assets
          path: assets

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      # use a community action
      - name: Create Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          # auto set by github
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ steps.date.outputs.date }}"
          prerelease: false
          # uses today's date
          title: "Data Release: ${{ steps.date.outputs.date }}"
          files: |
            README.md
            LICENSE
            assets/*
